name: environment.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.0
  - plotly
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - numpy
  - statsmodels
  - seaborn
  - r-dplyr
  - r-ggplot2
  - r-tidyverse
  - r-plotly
  - r-stringr
